# Generated by Django 5.2.3 on 2025-07-04 14:58

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='symmetric_key',
            field=models.BinaryField(default=chat.models.generate_symmetric_key),
        ),
    ]
