# Generated by Django 5.2.3 on 2025-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_symmetric_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='If the message contains only a link or externally hosted file', null=True),
        ),
    ]
