# Generated by Django 5.2.3 on 2025-07-08 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional alternate name shown in chats', max_length=50)),
                ('avatar', models.ImageField(blank=True, help_text='User’s profile picture', null=True, upload_to='avatars/%Y/%m/%d/')),
                ('presence', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('do_not_disturb', 'Do Not Disturb')], default='available', help_text='Current availability status', max_length=16)),
                ('show_online', models.BooleanField(default=True, help_text="Allow others to see when you're online")),
                ('show_last_seen', models.BooleanField(default=True, help_text='Allow others to see your last seen timestamp')),
                ('show_typing', models.BooleanField(default=True, help_text='Allow others to see typing indicator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
